first draft for user_info [close #34]
PyDrocsid/documentation pull request #60
Opened 2021-05-14 20:44 UTC by FlorianJSa

2021-06-15 15:54 UTC, 4norak requested changes

2021-06-15 15:54 UTC, 4norak commented on docs/cogs/information/user_info.md
> +|`user`||The user whose information is requested. If omitted, the requesting user receives their own information via direct messages.|
```suggestion
|`user`||The user whose information is requested. If omitted, the requesting user receives their own information via as a direct message.|
```

2021-06-15 15:54 UTC, 4norak commented on docs/cogs/information/user_info.md
> +The `.joined` command shows a rough estimate of how much time has passed since the last verification of a given member. If no `Verified` role has been configured yet, this estimate refers to the last
Keep in mind that the actual calculation is probably going to be changed soon, so either remember to update this accordingly or make the documentation more generic here

2021-06-15 15:54 UTC, 4norak commented on docs/cogs/information/user_info.md
> +|`user`||The user whose log is requested. If omitted, the requesting user receives their own log via direct messages.|
```suggestion
|`user`||The user whose log is requested. If omitted, the requesting user receives their own log as a direct message.|
```

2021-06-15 15:54 UTC, 4norak commented on docs/cogs/information/user_info.md
> +- Moderation actions:
```suggestion
- Passive moderation actions:
```

2021-06-20 21:03 UTC, Tristan-H11 requested changes

2021-06-20 21:03 UTC, Tristan-H11 commented on docs/cogs/information/user_info.md
>  # User Info
```suggestion
# User info
```

2021-06-20 21:03 UTC, Tristan-H11 commented on docs/cogs/information/user_info.md
> +This cog contains some commands to show information about Discord user accounts.
```suggestion
This cog contains commands to show information about Discord user accounts.
```

2021-06-20 21:03 UTC, Tristan-H11 commented on docs/cogs/information/user_info.md
> +The `.user` command shows general information about a given user.
```suggestion
The `.user` command shows general information about the requested user.
```

2021-06-20 21:03 UTC, Tristan-H11 commented on docs/cogs/information/user_info.md
> +|`user`||The user whose information is requested. If omitted, the requesting user receives their own information via as a direct message.|
```suggestion
|`user`||The user whose information is requested. If omitted, the requesting user receives their own information via a direct message.|
```

2021-06-20 21:18 UTC, Tristan-H11 approved these changes, later dismissed

2021-06-20 21:26 UTC, 4norak requested changes

2021-06-20 21:26 UTC, 4norak commented on docs/cogs/information/user_info.md
> +|`user`||The user whose information is requested. If omitted, the requesting user receives their own information via a direct message.|
```suggestion
|`user`||The user whose information is requested. If omitted, the requesting user receives their own information as a direct message.|
```

2021-06-20 21:28 UTC, 4norak approved these changes

2021-06-20 21:28 UTC, merged